name: My Test Workflow
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Fetch code from repo
              uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Fetch code from repo
              uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
            - name: Install dependencies
              run: npm ci
            - name: Build project
              run: npm run build
            - name: Deploy to production
              run: echo "Deploying to production"
            